"""
    Offer Enrollment Service

    A set of API endpoints that allow you to get information about offer enrollment  # noqa: E501

    The version of the OpenAPI document: 1.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_offer_enrollment_sdk
from osis_offer_enrollment_sdk.model.enrollment import Enrollment
globals()['Enrollment'] = Enrollment
from osis_offer_enrollment_sdk.model.enrollment_list_all_of import EnrollmentListAllOf


class TestEnrollmentListAllOf(unittest.TestCase):
    """EnrollmentListAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnrollmentListAllOf(self):
        """Test EnrollmentListAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnrollmentListAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
