"""
    Offer Enrollment Service

    A set of API endpoints that allow you to get information about offer enrollment  # noqa: E501

    The version of the OpenAPI document: 1.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_offer_enrollment_sdk
from osis_offer_enrollment_sdk.model.inscription import Inscription
globals()['Inscription'] = Inscription
from osis_offer_enrollment_sdk.model.mes_inscriptions import MesInscriptions


class TestMesInscriptions(unittest.TestCase):
    """MesInscriptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMesInscriptions(self):
        """Test MesInscriptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MesInscriptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
