"""
    Offer Enrollment Service

    A set of API endpoints that allow you to get information about offer enrollment  # noqa: E501

    The version of the OpenAPI document: 1.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_offer_enrollment_sdk
from osis_offer_enrollment_sdk.model.inscription import Inscription


class TestInscription(unittest.TestCase):
    """Inscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInscription(self):
        """Test Inscription"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Inscription()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
